In [1]:
import sys
import os
sys.path.insert(0, "compass")

import random
import cProfile
import numpy as np
from parameters import FLAGS
from model import CompassModel

# Set seeds for reproducibility
random.seed(3)
np.random.seed(3)

In [2]:
import os
import pickle

dir_path = os.getcwd()
file_path = os.path.join(dir_path, "compass/maps/ijburg/agents_ijburg.pickle")
file = open(file_path, "rb")
data = pickle.load(file)

/home/jiqi/.local/share/virtualenvs/school-choice---understanding-segregation-rFYzdyjw/lib/python3.8/site-packages/geopandas/_compat.py:111: UserWarning: The Shapely GEOS version (3.9.1-CAPI-1.14.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(

In [8]:
new_path = os.path.join(dir_path, "compass/maps/ijburg/agents_ijburg_new.pickle")
file_new = open(new_path, "wb")
pickle.dump(obj=data, file=file_new)

In [3]:
data.keys()

dict_keys(['neighbourhoods', 'schools', 'households', 'neighbourhoods_gpd', 'agents', 'perc_of_actual', 'distances', 'closest_schools', 'furthest_schools'])

In [7]:
pip list | grep pandas

geopandas            0.10.2
pandas               1.4.0
Note: you may need to restart the kernel to use updated packages.

In [32]:
sn = data["neighbourhoods_gpd"]
sn

,Buurt_code,geometry,object,x,y,shape,size,color,group
0,M35a,"POLYGON ((554838.272 6867253.819, 555099.094 6...",Neighbourhood,"[554838.2720533618, 555099.0936202904, 555377....","[6867253.818639372, 6867143.87894571, 6867060....",None,None,black,NaN
1,M35b,"POLYGON ((553483.403 6865955.240, 553997.699 6...",Neighbourhood,"[553483.4025309169, 553997.6985783817, 554117....","[6865955.240444446, 6866416.455108272, 6866312...",None,None,black,NaN
2,M35c,"POLYGON ((554875.007 6865285.888, 555085.290 6...",Neighbourhood,"[554875.0074853235, 555085.2900034321, 555291....","[6865285.888117213, 6865474.183407622, 6865286...",None,None,black,NaN
3,M51a,"POLYGON ((556378.043 6863592.522, 556549.141 6...",Neighbourhood,"[556378.0432500143, 556549.1413073635, 557137....","[6863592.521984882, 6863489.739504042, 6863056...",None,None,black,NaN
4,M35e,"POLYGON ((556738.050 6867046.885, 557126.889 6...",Neighbourhood,"[556738.0504832397, 557126.8894645808, 556158....","[6867046.88530454, 6866313.6365872985, 6865228...",None,None,black,NaN
5,M35f,"POLYGON ((555693.874 6864936.469, 556041.079 6...",Neighbourhood,"[555693.8736595988, 556041.0791513831, 556158....","[6864936.468927062, 6865326.536195542, 6865228...",None,None,black,NaN
6,M50b,"POLYGON ((558782.433 6865083.380, 560912.754 6...",Neighbourhood,"[558782.4329316582, 560912.7540269691, 560917....","[6865083.379895771, 6865249.6148931645, 686513...",None,None,black,NaN
7,M50e,"POLYGON ((557290.306 6866005.371, 558713.192 6...",Neighbourhood,"[557290.3064770651, 558713.1922083849, 558782....","[6866005.371193786, 6866001.543016469, 6865083...",None,None,black,NaN
8,M50c,"POLYGON ((558713.192 6866001.543, 560873.904 6...",Neighbourhood,"[558713.1922083849, 560873.9035246823, 560885....","[6866001.543016469, 6866168.708454323, 6865867...",None,None,black,NaN
9,M50f,"POLYGON ((556738.050 6867046.885, 558204.907 6...",Neighbourhood,"[556738.0504832397, 558204.9074134227, 560792....","[6867046.88530454, 6867271.686260384, 6868288....",None,None,black,NaN
10,M51c,"POLYGON ((556680.610 6864077.476, 557029.930 6...",Neighbourhood,"[556680.6096259904, 557029.9301880997, 557193....","[6864077.476167585, 6864479.713229452, 6864342...",None,None,black,NaN
11,M50a,"POLYGON ((558809.818 6864720.482, 560917.986 6...",Neighbourhood,"[558809.8175263933, 560917.9860430363, 560945....","[6864720.481859643, 6865134.963414903, 6864491...",None,None,black,NaN
12,M50d,"POLYGON ((558130.991 6864888.168, 558782.433 6...",Neighbourhood,"[558130.991271536, 558782.4329316582, 558809.8...","[6864888.16751893, 6865083.379895771, 6864720....",None,None,black,NaN
13,M50g,"POLYGON ((557744.267 6865148.816, 558130.991 6...",Neighbourhood,"[557744.2673605202, 558130.991271536, 558848.2...","[6865148.816289032, 6864888.16751893, 6863564....",None,None,black,NaN
14,M51b,"POLYGON ((556378.043 6863592.522, 556431.699 6...",Neighbourhood,"[556378.0432500143, 556431.6992445766, 556680....","[6863592.521984882, 6863790.80111397, 6864077....",None,None,black,NaN

In [37]:
sn.dtypes

Buurt_code      object
geometry      geometry
object          object
x               object
y               object
shape           object
size            object
color           object
group          float64
dtype: object

In [40]:
shape = sn.iloc[0]["geometry"]
type(shape)

shapely.geometry.polygon.Polygon

In [42]:
data["agents"].describe()

             group
count  8482.000000
mean      0.337303
std       0.472817
min       0.000000
25%       0.000000
50%       0.000000
75%       1.000000
max       1.000000